### ISSUE TITLE
Not sure the which version of the stable-baseline3 you are using

### ISSUE THREAD

**Issue by harryting-yiting** [RU-Automated-Reasoning-Group/GCRL-LTL#5]
Hi,

I am trying to run your code. 

It seems that your code relies on a specific version of the SB3 library.

Do you mind to clarify it in your readme?😀

Best

**Comment by Roadsong** [comment]
Hi,
Can you try 1.3.0?  Could you please let me know on which part the newer version of sb3 doesn't work? Thanks.

**Comment by harryting-yiting** [comment]
Thanks for your reply.

I just made it work. 
For the zone environment, I use
```
python=3.7
stable-baselines3==1.6.2
```
Because any version after 1.6.2 dose not support shared_layers in `mlp_extractor`, which is used in your PPO polices. For reference, please refer to https://github.com/DLR-RM/stable-baselines3/releases.
